### read all users
GET http://localhost:4000/user-api/users

###read user by object id
GET http://localhost:4000/user-api/users/697dbb0b0e3fb9daf28e2701

###create user
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "username":"shri",
    "password":"shri",
    "age":21
}

###Update user

PUT http://localhost:4000/user-api/users/697dbe732ab5eb4d6ddf8dc5
Content-Type: application/json

{
    "username":"shri",
    "password":"shri",
    "age":23
}

###Delete user by object id
DELETE http://localhost:4000/user-api/users/697dbe732ab5eb4d6ddf8dc5

###read products
GET http://localhost:4000/product-api/products

###create product
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
    "pid":100,
    "productName":"Laptop",
    "price":20000
}

###update product
PUT http://localhost:4000/product-api/products/697dd1cd81c0c3ac000c359b
Content-Type: application/json

{
    "pid":100,
    "productName":"Mouse",
    "price":5000
}

###user authentication req

POST http://localhost:4000/user-api/auth
Content-Type: application/json

{
    "username":"shri",
    "password" :"shri"
}

###req for protected route
GET http://localhost:4000/user-api/test
